version: '3'
services:
  server:
    build:
      context: .
    ports:
      - "5000:5000"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # This will persist MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: example
      PMA_ABSOLUTE_URI: http://localhost:8081/

volumes:
  mysql_data:  # Declaring the volume
