apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2  # Number of pods you want
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: meriemlearn/repo:latestt  # Image from registry
          ports:
            - containerPort: 5000  # Port the container is listening on
      imagePullSecrets:
        - name: docker-registry-secret    