apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-{{ .Values.blueGreen.active }}
  labels:
    app: mysql
    environment: {{ .Values.blueGreen.active }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
      environment: {{ .Values.blueGreen.active }}
  template:
    metadata:
      labels:
        app: mysql
        environment: {{ .Values.blueGreen.active }}
    spec:
      containers:
        - name: mysql-container
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-{{ .Values.blueGreen.active }}-pvc
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
        {{- end }}
