apiVersion: v1
kind: Service
metadata:
  name: my-app-servicee
spec:
  selector:
    app: my-app
    environment: {{ .Values.blueGreen.active }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
