apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 2  # Number of pods you want
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: meriemlearn/repo:mysql  # Image from registry
          ports:
            - containerPort: 3306   # Port the container is listening on
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example  # Set your root password here
            - name: MYSQL_DATABASE
              value: mydatabase  # Define the database name
            - name: MYSQL_USER
              value: user  # Define a user
            - name: MYSQL_PASSWORD
              value: password  # Define the user's password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql  # Mount for persistent data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc  # Reference a PVC for data persistence
      imagePullSecrets:
        - name: docker-registry-secret

