apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306  # Port your container is listening on
      nodePort: 30002   # Port to access from outside
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
