apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app: mysql
    type: standalone
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 5Gi
