apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 2  # Number of pods you want
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin-container
          image: meriemlearn/repo:phpmyadmin  # Image from registry
          ports:
            - containerPort: 8081   # Port the container is listening on
      imagePullSecrets:
        - name: docker-registry-secret    