apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081  # Port your container is listening on
      nodePort: 30001   # Port to access from outside
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
