apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081  # Port your container is listening on
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
