replicaCount: 2

image:
  repository: meriemlearn/repo
  tag: server
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

blueGreen:
  active: blue  # Current active environment: 'blue' or 'green'
  blueSuffix: "-blue"
  greenSuffix: "-green"

imagePullSecrets:
  - name: docker-registry-secret

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
