name: Tag and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Compose Services
      run: docker compose build

    - name: Tag and Push Docker Images
      run: |
        # Tag and push the server image
        docker tag meriemlearn/repo:server ${DOCKER_USERNAME}/repo:server
        docker push ${DOCKER_USERNAME}/repo:server

        # Tag and push the mysql image (official to your repo)
        docker pull mysql:latest
        docker tag mysql:latest ${DOCKER_USERNAME}/repo:mysql
        docker push ${DOCKER_USERNAME}/repo:mysql

        # Tag and push the phpmyadmin image (official to your repo)
        docker pull phpmyadmin/phpmyadmin
        docker tag phpmyadmin/phpmyadmin ${DOCKER_USERNAME}/repo:phpmyadmin
        docker push ${DOCKER_USERNAME}/repo:phpmyadmin

  deploy-to-k8s:
    runs-on: ubuntu-22.04
    needs: build-and-push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group k8_group --name k8


      - name: Deploy to Azure Kubernetes Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Wait for Deployment to complete
        run: |
          kubectl rollout status deployment/my-app



