name: CI/CD Docker Compose Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: meriemlearn/repo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: latest  # or your custom tag like "v1.0.0"

  
  deploy-to-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        run: |
          mkdir -p $HOME/.kube  # Create the .kube directory
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Wait for Deployment to complete
        run: |
          kubectl rollout status deployment/my-app
 


