name: CI/CD Docker Compose Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: meriemlearn/repo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: latest  # or your custom tag like "v1.0.0"

  

  deploy-to-k8s:
    runs-on: ubuntu-22.04
    needs: build-and-push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group k8_group --name k8


      - name: Deploy to Azure Kubernetes Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Wait for Deployment to complete
        run: |
          kubectl rollout status deployment/my-app



