name: CI/CD Docker Compose Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: meriemlearn/repo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: latest  # or your custom tag like "v1.0.0"

  

  deploy-to-k8s:
    runs-on: ubuntu-22.04
    needs: build-and-push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/azure-cli-action@v1

      - name: Log in to Azure
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group your-resource-group --name your-aks-cluster

      - name: Deploy to Azure Kubernetes Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Wait for Deployment to complete
        run: |
          kubectl rollout status deployment/my-app



